fixes:
  - "/home/runner/work/dftd4/dftd4::"

# Only cover core library
ignore:
  - "app/"
  - "assets/"
  - "build/"
  - "config/"
  - "doc/"
  - "include/"
  - "man/"
  - "python/"
  - "subprojects/"
  - "test/"

