# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/PlasmaFAIR/fortitude-pre-commit
    rev: v0.9.0
    hooks:
      - id: fortitude
        args: ["--fix", "--preview"]
