set(CMAKE_IMPORT_FILE_VERSION 1)

set(
  DFTD4_INCLUDEDIRS
  "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_INCLUDEDIR@"
  "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_INCLUDEDIR@/@module-dir@"
)
find_library(
  DFTD4_LIBRARIES
  "@PROJECT_NAME@"
  PATHS "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@"
  NO_DEFAULT_PATH
)
set(
  DFTD4_DEPENDENCIES
  "$<$<BOOL:${DFTD4_USE_MCTCLIB}>:mctc-lib::mctc-lib>"
  "$<$<BOOL:${DFTD4_USE_MULTICHARGE}>:multicharge::multicharge>"
  "$<$<BOOL:${DFTD4_WITH_OpenMP}>:OpenMP::OpenMP_Fortran>"
  "LAPACK::LAPACK"
)

add_library(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE IMPORTED)
add_library(@PROJECT_NAME@::@PROJECT_NAME@ ALIAS @PROJECT_NAME@::@PROJECT_NAME@-lib)
target_link_libraries(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE ${DFTD4_LIBRARIES} ${DFTD4_DEPENDENCIES})
target_include_directories(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE ${DFTD4_INCLUDEDIRS})
